### ISSUE TITLE
Separate UI & XPO/EFCore classes for XAF

### ISSUE THREAD

**Issue by petre-c** [biohazard999/Para.FluentModelBuilder#2]
Hello, [Manuel](@biohazard999),
This issue may not belong here so please move it to the proper place as you see fit.

Can you recommend a method to separate UI classes from the Domain Model classes in XAF?
So, effectively, create separate Domain Entities in XPO / EFCore & separate UI classes?

This, in my mind, would enable DDD-zation of persistent types and still allow us to take advantage of XAF's UI generation capabilities.

Have a great day!
- Petre

**Comment by biohazard999** [comment]
I think i answered the question in #1

**Comment by petre-c** [comment]
Right 🙂
